"use client";

import React from "react";
import { FileText, Database } from "lucide-react";

export default function ArtifactsPage() {
  return (
    <div className="p-10 max-w-5xl mx-auto space-y-10">
      <h1 className="text-3xl font-bold tracking-tight premium-gradient-text">Intelligence Artifacts</h1>
      <div className="p-20 flex flex-col items-center justify-center text-center space-y-4 glass-card rounded-3xl">
         <FileText className="h-12 w-12 text-zinc-400" />
         <h3 className="text-lg font-bold">Knowledge Base</h3>
         <p className="text-sm text-zinc-500">Raw documents and scraped data artifacts generated by your agents appear here.</p>
      </div>
    </div>
  );
}
